onlineExam/onlineExam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from student import views

urlpatterns = [
    #管理员登陆
    path('admin/', admin.site.urls),
    #学生登陆
    url(r'^studentLogin/',views.studentLogin),
    #教师登陆
    url(r'^teacherLogin/',views.teacherLogin),
    #默认访问首页
    url(r'^$',views.index),
    url(r'^toIndex/$',views.toIndex),
    url('showGrade',views.showGrade),
    url('queryStudent',views.queryStudent),
    url(r'^startExam/$',views.startExam),
    url(r'^calGrade/$',views.calGrade),
    url(r'^logout/$',views.logOut),
]

onlineExam/student/models.py
from django.db import models

# Create your models here.

# 为性别,学院 指定备选字段
SEX=(
    ('男','男'),
    ('女','女'),
)
DEPT=(
    ('计算机与通信学院','计算机与通信学院'),
    ('电气与自动化学院','电气与自动化学院'),
    ('外国语学院','外国语学院'),
    ('理学院','理学院'),
)

class Student(models.Model):
    id=models.CharField('学号',max_length=20,primary_key=True)
    name=models.CharField('姓名',max_length=20)
    sex=models.CharField('性别',max_length=4,choices=SEX,default='男')
    dept=models.CharField('学院',max_length=20,choices=DEPT,default=None)
    major=models.CharField('专业',max_length=20,default=None)
    password=models.CharField('密码',max_length=20,default='111')
    email=models.EmailField('邮箱',default=None)
    birth=models.DateField('出生日期')

    class Meta:
        db_table='student'
        verbose_name='学生'
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.id;

class Teacher(models.Model):
    id=models.CharField("教工号",max_length=20,primary_key=True)
    name=models.CharField('姓名',max_length=20)
    sex=models.CharField('性别',max_length=4,choices=SEX,default='男')
    dept=models.CharField('学院',max_length=20,choices=DEPT,default=None)
    email=models.EmailField('邮箱',default=None)
    password=models.CharField('密码',max_length=20,default='000000')
    birth=models.DateField('出生日期')

    class Meta:
        db_table='teacher'
        verbose_name='教师'
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.name;

class Question(models.Model):

    ANSWER=(
        ('A','A'),
        ('B','B'),
        ('C','C'),
        ('D','D'),
    )
    LEVEL={
        ('1','easy'),
        ('2','general'),
        ('3','difficult'),
    }
    id = models.AutoField(primary_key=True)
    subject = models.CharField('科目', max_length=20)
    title = models.TextField('题目')
    optionA=models.CharField('A选项',max_length=30)
    optionB=models.CharField('B选项',max_length=30)
    optionC=models.CharField('C选项',max_length=30)
    optionD=models.CharField('D选项',max_length=30)
    answer=models.CharField('答案',max_length=10,choices=ANSWER)
    level=models.CharField('等级',max_length=10,choices=LEVEL)
    score=models.IntegerField('分数',default=1)

    class Meta:
        db_table='question'
        verbose_name='单项选择题库'
        verbose_name_plural=verbose_name
    def __str__(self):
        return '<%s:%s>'%(self.subject,self.title);

class Paper(models.Model):
    #题号pid 和题库为多对多的关系
    pid=models.ManyToManyField(Question)#多对多
    tid=models.ForeignKey(Teacher,on_delete=models.CASCADE)#添加外键
    subject=models.CharField('科目',max_length=20,default='')
    major=models.CharField('考卷适用专业',max_length=20)
    examtime=models.DateTimeField()


    class Meta:
        db_table='paper'
        verbose_name='试卷'
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.major;

class Grade(models.Model):
    sid=models.ForeignKey(Student,on_delete=models.CASCADE,default='')#添加外键
    subject=models.CharField('科目',max_length=20,default='')
    grade=models.IntegerField()

    def __str__(self):
        return '<%s:%s>'%(self.sid,self.grade);

    class Meta:
        db_table='grade'
        verbose_name='成绩'
        verbose_name_plural=verbose_name

onlineExam/templates/exam.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta http-equiv="content-type" content="text/html;charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>在线答题考试系统</title>

    <link href="../static/bootstrap-4.3.1-dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="../static/jquery-3.3.1.min.js"></script>

    <script src="../static/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>

    <script src="../static/js/jquery-1.11.3.min.js"></script>
    <script src="../static/js/jquery.countdown.js"></script>
    <!--时间js-->
    <link href="../static/css/main.css" rel="stylesheet" type="text/css" />

    <link href="../static/css/test.css" rel="stylesheet" type="text/css" />
<style>
.hasBeenAnswer {
	background: #5d9cec;
	color:#fff;
}
</style>

</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light ">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link"><h3>在线考试系统</h3></a>
        </li>

        <li class="nav-item active">
            <a class="nav-link"><h3>当前科目:{{ subject }}</h3></a>
        </li>
        <li style="position: fixed;right: 70px; font-size: 30px;color: #9fcdff">{{ student.name }}</li>

    </ul>
</nav>
<div class="main">
	<!--nr start-->
	<div class="test_main">
		<div class="nr_left">
			<div class="test">
				<form action="/calGrade/" method="post">
                <input type="hidden" name="sid" value="{{ student.id }}">
                <input type="hidden" name="subject" value="{{ subject }}">
					<div class="test_title">
						<p class="test_time">
							<i class="icon iconfont">&#xe6fb;</i><b class="alt-1">01:40</b>
						</p>
						<font><input type="submit" name="tijiao" value="交卷"></font>
					</div>

						<div class="test_content">
							<div class="test_content_title">
								<h2>单选题</h2>
								<p>
									<span>共</span><i class="content_lit">10</i><span>题，</span>
                                    <span>合计</span><i class="content_fs">10</i><span>分</span>
								</p>
							</div>
						</div>
						<div class="test_content_nr">
							<ul>
                                {% for paper1 in paper %}
                                   {% for test in paper1.pid.all %}
                                       <li id="{{ forloop.counter }}">
                                        <div class="test_content_nr_tt">
											<i>{{ forloop.counter}}</i><span>({{ test.score }}分)</span>
                                            <font>{{ test.title }}</font>

										</div>
                                       <div class="test_content_nr_main">
											<ul>
													<li class="option">
															<input type="radio" class="radioOrCheck" name="{{ test.id }}"
                                                            value="A"/>
														<label>A.
                                                            <p class="ue" style="display: inline;">{{ test.optionA }}</p>
														</label>
													</li>

													<li class="option">
															<input type="radio" class="radioOrCheck" name="{{ test.id }}"
                                                            value="B"/>
														<label>
															B.<p class="ue" style="display: inline;">{{ test.optionB }}</p>
														</label>
													</li>

													<li class="option">
															<input type="radio" class="radioOrCheck" name="{{ test.id }}"
                                                            value="C"/>
														<label>
															C.<p class="ue" style="display: inline;">{{ test.optionC }}</p>
														</label>
													</li>

													<li class="option">
															<input type="radio" class="radioOrCheck" name="{{ test.id }}"
                                                            value="D"/>
														<label>
															D.<p class="ue" style="display: inline;">{{ test.optionD }}</p>
														</label>
													</li>
											</ul>
										</div>
                                        </li>
                                   {% endfor %}
                                {% endfor %}
							</ul>
						</div>
				</form>
			</div>
		</div>

{#		<div class="nr_right">#}
{#			<div class="nr_rt_main">#}
{#				<div class="rt_nr1">#}
{#					<div class="rt_nr1_title">#}
{#						<h1>#}
{#							<i class="icon iconfont">&#xe692;</i>答题卡#}
{#						</h1>#}
{#						<p class="test_time">#}
{#							<i class="icon iconfont">&#xe6fb;</i><b class="alt-1">01:40</b>#}
{#						</p>#}
{#					</div>#}
{##}
{#						<div class="rt_content">#}
{#							<div class="rt_content_tt">#}
{#								<h2>单选题</h2>#}
{#								<p>#}
{#									<span>共</span><i class="content_lit">10</i><span>题</span>#}
{#								</p>#}
{#							</div>#}
{#							<div class="rt_content_nr answerSheet">#}
{#								<ul>#}
{#                                    {% for paper1 in paper %}#}
{#                                        {% for foo in paper1.pid.all %}#}
{#                                           <li><a href="#{{ forloop.counter }}">{{ forloop.counter }}</a></li>#}
{#                                        {% endfor %}#}
{#                                    {% endfor %}#}
{#								</ul>#}
{#							</div>#}
{#						</div>#}
{#				</div>#}
{##}
{#			</div>#}
{#		</div>#}
	</div>
	<!--nr end-->
	<div class="foot"></div>
</div>


<script>
	window.jQuery(function($) {
		"use strict";

		$('time').countDown({
			with_separators : false
		});
		$('.alt-1').countDown({
			css_class : 'countdown-alt-1'
		});
		$('.alt-2').countDown({
			css_class : 'countdown-alt-2'
		});

	});


	{% comment %}$(function() {
		$('li.option label').click(function() {
		debugger;
			var examId = $(this).closest('.test_content_nr_main').closest('li').attr('id'); // 得到题目ID
			var cardLi = $('a[href=#' + examId + ']'); // 根据题目ID找到对应答题卡
			// 设置已答题
			if(!cardLi.hasClass('hasBeenAnswer')){
				cardLi.addClass('hasBeenAnswer');
			}});
	});
{% endcomment %}
</script>


</body>
</html>

onlineExam/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">#}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="../static/bootstrap-4.3.1-dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="../static/jquery-3.3.1.min.js"></script>

    <script src="../static/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>

   <link href="../static/css/index.css" rel="stylesheet">

    <title>在线考试系统</title>

</head>
<body>

<nav class="navbar navbar-expand-sm bg-light navbar-light ">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="/toIndex/"><h3>在线考试系统 首页</h3></a>
        </li>

{#         <li class="nav-item active">#}
{#            <a class="nav-link" href="/toLogin/">学生登陆</a>#}
{##}
{#        </li>#}
{##}
{#            <li class="nav-item active">#}
{#            <a class="nav-link" href="/admin/">教师登陆</a>#}
{#            </li>#}
        <li>
            <button data-target="#stuModal" data-toggle="modal" class="btn btn-primary">学生登陆</button>
        </li>

        <li>
            <button data-target="#teaModal" data-toggle="modal" class="btn btn-primary">教师登陆</button>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/admin">管理员</a>
        </li>


        <li style="position: fixed;right: 70px; font-size: 40px;color: #9fcdff">{{ student.name }}{{ message }}</li>
       <a href="/logout/"><li style="position: fixed;right: 20px; font-size: 20px;top:22px;color:#cc1313">退出</li></a>

    </ul>
</nav>

<div class="container">

  <br>
  <!-- Nav pills -->
  <ul class="nav nav-pills" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="pill" href="#home">个人信息</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="pill" href="#menu1">考试信息</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="pill" href="#menu2">成绩查询</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active"><br>
      <h3>个人信息</h3>

        <table class="table">
    <thead>
      <tr>
        <th>属性</th>
        <th>信息</th>

      </tr>
    </thead>
    <tbody>
      <tr>
        <td>学号</td>
        <td>{{ student.id }}</td>

      </tr>
      <tr class="table-primary">
        <td>姓名</td>
        <td>{{ student.name }}</td>

      </tr>
      <tr class="table-success">
        <td>性别</td>
        <td>{{ student.sex }}</td>

      </tr>
      <tr class="table-danger">
        <td>学院</td>
        <td>{{ student.dept }}</td>

      </tr>

       <tr class="table-success">
        <td>专业</td>
        <td>{{ student.major }}</td>

      </tr>

      <tr class="table-warning">
        <td>邮箱地址</td>
        <td>{{ student.email }}</td>

      </tr>
      <tr class="table-active">
        <td>出生日期</td>
        <td>{{ student.birth }}</td>

      </tr>

    </tbody>
  </table>
    </div>

    <div id="menu1" class="container tab-pane fade"><br>
      <h3>考试信息</h3>
      <p></p>
        <table class="table">
    <thead>
      <tr>
          <th>学号</th>
        <th>姓名</th>
        <th>考试科目</th>
          <th>考试时间</th>
          <th>操作</th>
      </tr>
    </thead>
    <tbody>
    {#   遍历字典  paper #}
    {% for paper1 in paper %}

     <tr class="table-info">
          <td>{{ student.id }}</td>
          <td>{{ student.name }}</td>
          <td>{{ paper1.subject }}{{ paper2.subject }}</td>
          <td>{{ paper1.examtime }} {{ paper2.examtime }}</td>
          <td>
              <a href="/startExam/?sid={{ student.id }}&subject={{ paper1.subject }}">
              <button class="btn btn-primary" id="toExam+{{ paper1.subject }}">开始考试</button>
             </a>
          </td>
      </tr>
    {% endfor %}



    </tbody>
  </table>
    </div>

    <div id="menu2" class="container tab-pane fade"><br>
      <h3>考试成绩</h3>
      <p></p>
        <table class="table">
        <thead>
          <tr>
            <th>姓名</th>
            <th>科目</th>
            <th>成绩</th>

          </tr>
        </thead>
    <tbody>

    {% for grade1 in grade %}
        <tr class="table-primary">
        <td>{{ student.name }}</td>
        <td>{{ grade1.subject }}</td>
        <td>{{ grade1.grade }}</td>

      </tr>
    {% endfor %}




    </tbody>
  </table>
    </div>
  </div>
</div>


{#学生登录的模态对话框#}
<div class="modal fade" tabindex="-1" role="dialog" id="stuModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">学生登陆</h4>
            </div>
            <form class="form-horizontal" action="/studentLogin/" method="post">
            <div class="modal-body">

                    <div class="form-group">
                        <label class="col-sm-3 control-label">学生学号</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="id" placeholder="输入学号">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="addr" class="col-sm-3 control-label">密码</label>
                        <div class="col-sm-9">
                            <!--
                            <textarea id="addr" class="form-control" rows="3"></textarea>
                            -->
                            <input type="password" class="form-control" name="password" placeholder="输入密码">
                         </div>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="submit" class="btn btn-primary">登陆</button>
            </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

{#老师登录的模态对话框#}
<div class="modal fade" tabindex="-1" role="dialog" id="teaModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">教师登陆</h4>
            </div>
            <form class="form-horizontal" action="/teacherLogin/" method="post">
            <div class="modal-body">

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">教师工号</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="id" placeholder="输入学号">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="addr" class="col-sm-3 control-label">密码</label>
                        <div class="col-sm-9">
                            <!--
                            <textarea id="addr" class="form-control" rows="3"></textarea>
                            -->
                            <input type="password" name="password" placeholder="输入密码" class="form-control">
                         </div>
                    </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="submit" class="btn btn-primary">登陆</button>
            </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

</body>

<script>
    $("#toExam+{{ paper1.subject }}").click(function () {

    });
</script>
</html>

onlineExam/templates/showGrade.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="../static/bootstrap-4.3.1-dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="../static/jquery-3.3.1.min.js"></script>

    <script src="../static/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>


    <script src="../static/js/echarts.min.js"></script>

    <title>成绩</title>
</head>
<body>
 <table class="table">
            <thead>
              <tr>
                <th>学生学号</th>
                <th>考试科目</th>
                  <th>成绩</th>
              </tr>
            </thead>

            <tbody>
            {#   遍历字典  grade #}
            {% for grade in grade %}
            <tr class="table-info">
                <td>{{ grade.sid }}</td>
                <td>{{ grade.subject }}</td>
                <td>{{ grade.grade }}</td>
                </tr>
            {% endfor %}


            </tbody>

          </table>

<div id="main1" style="width: 700px;height:500px;"></div>
 <script type="text/javascript">
     var myChart1=echarts.init(document.getElementById('main1'));
    myChart1.setOption({
    title : {
        text: '{{ subject }}',
        subtext: '',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        left: 'left',

    },
    series : [
        {
            name: '{{ subject }}',
            type: 'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[
                {value:{{ data.data1 }}, name:'<60'},
                {value:{{ data.data2}}, name:'60-70'},
                {value:{{ data.data3 }}, name:'70-80'},
                {value:{{ data.data4 }}, name:'80-90'},
                {value:{{ data.data5 }}, name:'>90'}
            ],
            itemStyle: {
                emphasis: {
                    shadowBlur: 10,
                    shadowOffsetX: 0,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]

})
 </script>
</body>
</html>

onlineExam/templates/teacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{#     <link rel="icon" href="http://v3.bootcss.com/favicon.ico">#}

    <link href="../static/bootstrap-4.3.1-dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="../static/jquery-3.3.1.min.js"></script>

    <script src="../static/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>

    <script src="../static/js/echarts.min.js"></script>
    <title>教师页面</title>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-light navbar-light ">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link"><h3>在线考试系统</h3></a>
        </li>

{#         <li class="nav-item active">#}
{#            <a class="nav-link" href="/toLogin/">学生登陆</a>#}
{##}
{#        </li>#}
{##}
{#            <li class="nav-item active">#}
{#            <a class="nav-link" href="/admin/">教师登陆</a>#}
{#            </li>#}
        <li>
            <a href="/logout/"><button data-target="#myModal" data-toggle="modal" class="btn btn-primary">退出</button></a>
        </li>

        <li style="position: fixed;right:70px; font-size: 40px;color: #9fcdff">{{ message }}{{ teacher.name }}</li>

    </ul>
</nav>

<div class="container">

  <br>
  <!-- Nav pills -->
  <ul class="nav nav-pills" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="pill" href="#home">个人信息</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="pill" href="#menu1">成绩统计</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" data-toggle="pill" href="#menu2">成绩查询</a>
    </li>
      <li class="nav-item">
      <a class="nav-link" href="/admin/student/paper/add/">组卷</a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active"><br>
      <h3>个人信息</h3>
      <p>登陆成功后可查看我的个人信息哦.</p>
        <table class="table">
    <thead>
      <tr>
        <th>属性</th>
        <th>信息</th>

      </tr>
    </thead>
    <tbody>
      <tr>
        <td>教工号</td>
        <td>{{ teacher.id }}</td>

      </tr>
      <tr class="table-primary">
        <td>姓名</td>
        <td>{{ teacher.name }}</td>

      </tr>
      <tr class="table-success">
        <td>性别</td>
        <td>{{ teacher.sex }}</td>

      </tr>
      <tr class="table-danger">
        <td>学院</td>
        <td>{{ teacher.dept }}</td>

      </tr>

      <tr class="table-warning">
        <td>邮箱地址</td>
        <td>{{ teacher.email }}</td>

      </tr>
      <tr class="table-active">
        <td>出生日期</td>
        <td>{{ teacher.birth }}</td>

      </tr>

    </tbody>
  </table>
    </div>

    <div id="menu1" class="container tab-pane fade"><br>
      <h3>成绩统计</h3>
      <p></p>
        <table class="table">
            <thead>
              <tr>

                <th>姓名</th>
                <th>考试科目</th>
                  <th>考试时间</th>
                  <th>操作</th>
              </tr>
            </thead>

            <tbody>
            {#   遍历字典  paper #}
            {% for paper1 in paper %}
             <tr class="table-info">

                  <td>{{ teacher.name }}</td>
                  <td>{{ paper1.subject }}</td>
                  <td>{{ paper1.examtime }}</td>
                 <td><a href="/showGrade/?subject={{ paper1.subject }}">
                     <button type="button" class="btn btn-primary"
                 data-toggle="collapse" data-target="#demo">查看学生成绩</button></a>
                 </td>

            {#          <td><button class="btn btn-primary">开始考试</button></td>#}
              </tr>

            {% endfor %}


            </tbody>

        </table>

    <div id="main" style="width: 800px;height:500px;"></div>

    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));


        // 指定图表的配置项和数据
        var option = {
    legend: {},
    tooltip: {},
    dataset: {
        // 提供一份数据。
        source: [
            ['product', '软件工程', '数据库原理'],
            ['<60', {{ data_1.data1 }}, {{ data_2.data6 }}],
            ['60<=成绩<70', {{ data_1.data2 }}, {{ data_2.data7 }}],
            ['70<=成绩<80', {{ data_1.data3 }}, {{ data_2.data8 }}],
            ['80<=成绩<90', {{ data_1.data4 }}, {{ data_2.data9 }}],
            ['90<=成绩', {{ data_1.data5 }}, {{ data_2.data10 }}]

        ]
    },
    // 声明一个 X 轴，类目轴（category）。默认情况下，类目轴对应到 dataset 第一列。
    xAxis: {type: 'category'},
    // 声明一个 Y 轴，数值轴。
    yAxis: {},
    // 声明多个 bar 系列，默认情况下，每个系列会自动对应到 dataset 的每一列。
    series: [
        {type: 'bar'},
        {type: 'bar'}
    ]
};
        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);

    </script>
    </div>

    <div id="menu2" class="container tab-pane fade"><br>
      <h3>考试成绩</h3>

{#        form表单#}
      <div class="container">
          <form action="/queryStudent/" method="get">
              <input type="hidden" name="tid" value="{{ teacher.id }}">
              <div class="row">
                  <div class="col-sm-2">
                      <div class="form-group">
                          <label>学号</label>
                          <input type="text" name="id" class="form-control" placeholder="请输入学号">
                      </div>
                  </div>

                  <div class="col-sm-2 offset-1">
                      <label for="">性别</label>

                      <div class="radio">
{#                          使用单选框的checked属性，默认 全部 单选按钮被选中#}
                            <label><input type="radio" name="sex" value="" checked>全部</label>
                        </div>
                      <div class="radio">
                            <label><input type="radio" name="sex" value="男" >男</label>
                        </div>
                        <div class="radio">
                          <label><input type="radio" name="sex" value="女">女</label>
                        </div>
                  </div>
                  <div class="col-sm-2 offset-1">
                      <label for="">科目</label>
                      <input type="text" name="subject" placeholder="输入科目名称">
                  </div>

                  <div class="col-sm-2 offset-2">
                      <button class="btn btn-success" type="submit">search</button>
                  </div>
              </div>
          </form>
      </div>

{#    搜到的学生信息#}
        <div class="container">
            <table class="table">
                <thead>
                  <tr>
                      <th>学号</th>
                    <th>姓名</th>
                      <th>专业</th>
                    <th>科目</th>
                    <th>成绩</th>
                  </tr>
                </thead>
                <tbody>

                {% for result1 in result %}
                <tr class="table-primary">
                    <td>{{ result1.id }}</td>
                    <td>{{ result1.name }}</td>
                    <td>{{ result1.major }}</td>
                    <td>{{ result1.subject }}</td>
                    <td>{{ result1.grade }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div id="menu3" class="container tab-pane fade"><br>
      <h3>题库</h3>
      <p>题库</p>
    </div>
  </div>
</div>
</body>
</html>

onlineExam/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试成绩页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="../static/bootstrap-4.3.1-dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="../static/jquery-3.3.1.min.js"></script>

    <script src="../static/bootstrap-4.3.1-dist/js/bootstrap.min.js"></script>

</head>
<body>
<div class="container">
    <table class="table">
        <thead>
          <tr>
              <th>学号</th>
            <th>姓名</th>
              <th>专业</th>
            <th>科目</th>
            <th>成绩</th>
          </tr>
        </thead>
    <tbody>

    {% for result1 in result %}
    <tr class="table-primary">
        <td>{{ result1.id }}</td>
        <td>{{ result1.name }}</td>
        <td>{{ result1.major }}</td>
        <td>{{ result1.subject }}</td>
        <td>{{ result1.grade }}</td>


{#        <td>#}
{#            {% for grade1 in result1.grade_set.all %}#}
{##}
{#                <span>{{ grade1.grade }}</span>#}
{##}
{##}
{#            {% endfor %}#}
{#        </td>#}

    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

</body>
</html>